version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "3306:3000"
    volumes:
        - .:/app/dist
    command: 'yarn start'
