export const CREATE = [
  {
    model: 'firstName',
    required: true,
    dropdown: false,
    message: 'First Name is required.',
  },
  {
    model: 'middleName',
    required: true,
    dropdown: false,
    message: 'Middle Name is required.',
  },
  {
    model: 'lastName',
    required: true,
    dropdown: false,
    message: 'Last Name is required.',
  },
  {
    model: 'birthDate',
    required: true,
    dropdown: false,
    message: 'Birth Date is required.',
  },
  {
    model: 'birthPlace',
    required: true,
    dropdown: false,
    message: 'Birth Place is required.',
  },
  {
    model: 'password',
    required: true,
    dropdown: false,
    message: 'Password is required.',
  },
  {
    model: 'passwordConfirm',
    required: true,
    dropdown: false,
    message: 'Password Confirm is required.',
  },
  {
    model: 'pinCode',
    required: true,
    dropdown: false,
    message: 'PIN Code is required.',
  },
  {
    model: 'pinCodeConfirm',
    required: true,
    dropdown: false,
    message: 'PIN Code Confirm is required.',
  },
  {
    model: 'address1',
    required: true,
    dropdown: false,
    message: 'Primary Address is required.',
  },
  {
    model: 'address2',
    required: true,
    dropdown: false,
    message: 'Secondary Address is required.',
  },
  {
    model: 'zipCode',
    required: true,
    dropdown: false,
    message: 'Zip Code is required.',
  },
  {
    model: 'selectedRegion',
    required: true,
    dropdown: true,
    message: 'Region is required.',
  },
  {
    model: 'selectedProvince',
    required: true,
    dropdown: true,
    message: 'Province is required.',
  },
  {
    model: 'selectedCity',
    required: true,
    dropdown: true,
    message: 'City is required.',
  },
  {
    model: 'selectedRole',
    required: true,
    dropdown: true,
    message: 'Role is required.',
  },
  {
    model: 'selectedGender',
    required: true,
    dropdown: true,
    message: 'Gender is required.',
  },
  {
    model: 'selectedContactType',
    required: true,
    dropdown: true,
    message: 'Contact Type is required.',
  },
  {
    model: 'selectedAddressType',
    required: true,
    dropdown: true,
    message: 'Address Type is required.',
  },
]

export const UPDATE = [
  {
    model: 'firstName',
    required: true,
    dropdown: false,
    message: 'First Name is required.',
  },
  {
    model: 'middleName',
    required: true,
    dropdown: false,
    message: 'Middle Name is required.',
  },
  {
    model: 'lastName',
    required: true,
    dropdown: false,
    message: 'Last Name is required.',
  },
  {
    model: 'birthDate',
    required: true,
    dropdown: false,
    message: 'Birth Date is required.',
  },
  {
    model: 'birthPlace',
    required: true,
    dropdown: false,
    message: 'Birth Place is required.',
  },
  {
    model: 'address1',
    required: true,
    dropdown: false,
    message: 'Primary Address is required.',
  },
  {
    model: 'address2',
    required: true,
    dropdown: false,
    message: 'Secondary Address is required.',
  },
  {
    model: 'zipCode',
    required: true,
    dropdown: false,
    message: 'Zip Code is required.',
  },
  {
    model: 'selectedRegion',
    required: true,
    dropdown: true,
    message: 'Region is required.',
  },
  {
    model: 'selectedProvince',
    required: true,
    dropdown: true,
    message: 'Province is required.',
  },
  {
    model: 'selectedCity',
    required: true,
    dropdown: true,
    message: 'City is required.',
  },
  {
    model: 'selectedRole',
    required: true,
    dropdown: true,
    message: 'Role is required.',
  },
  {
    model: 'selectedGender',
    required: true,
    dropdown: true,
    message: 'Gender is required.',
  },
  {
    model: 'selectedContactType',
    required: true,
    dropdown: true,
    message: 'Contact Type is required.',
  },
  {
    model: 'selectedAddressType',
    required: true,
    dropdown: true,
    message: 'Address Type is required.',
  },
]
